from pathlib import Path

# ─────────────────────────────────────────────
#  PROJECT ROOT (auto-resolved)
# ─────────────────────────────────────────────
ROOT = Path(__file__).parent

# ─────────────────────────────────────────────
#  DATA PATHS
# ─────────────────────────────────────────────
class DataPaths:
    RAW_DIR        = ROOT / "data" / "raw"
    PROCESSED_DIR  = ROOT / "data" / "processed"

    # ── Files you download from BV-BRC ──────────────────────────────────
    #  Step 1: AMR Phenotype (resistance labels)
    AMR_PHENOTYPE  = RAW_DIR / "amr_phenotype.csv"

    #  Step 2: Specialty Genes (gene presence/absence features)
    SP_GENES       = RAW_DIR / "sp_genes.csv"

    # ── Files generated by DataController ───────────────────────────────
    FEATURE_MATRIX = PROCESSED_DIR / "feature_matrix.csv"
    GENE_LIST      = PROCESSED_DIR / "gene_list.txt"

# ─────────────────────────────────────────────
#  ORGANISM / EXPERIMENT SETTINGS
# ─────────────────────────────────────────────
class BioSettings:
    ORGANISM       = "Acinetobacter baumannii"
    TAXON_ID       = 470                 # NCBI Taxonomy ID for A. baumannii
    ANTIBIOTIC     = "meropenem"         # Target antibiotic (must match BV-BRC spelling)
    PHENOTYPE_COL  = "resistant_phenotype"
    GENOME_ID_COL  = "genome_id"
    GENE_COL       = "gene"
    RESISTANT_LABEL   = "Resistant"
    SUSCEPTIBLE_LABEL = "Susceptible"

# ─────────────────────────────────────────────
#  PREPROCESSING
# ─────────────────────────────────────────────
class PrepSettings:
    TEST_SIZE      = 0.20
    RANDOM_STATE   = 42
    MIN_GENE_PREVALENCE = 0.02   # Drop genes present in <2% of samples
    USE_SMOTE      = True        # Apply SMOTE to training set
    N_TOP_FEATURES = 25          # For chi2 ranking chart

# ─────────────────────────────────────────────
#  MODEL HYPERPARAMETERS
# ─────────────────────────────────────────────
class ModelConfig:
    RANDOM_STATE = 42
    CV_FOLDS     = 5

    XGBOOST = dict(
        n_estimators      = 300,
        max_depth         = 6,
        learning_rate     = 0.08,
        subsample         = 0.80,
        colsample_bytree  = 0.80,
        random_state      = 42,
        eval_metric       = "logloss",
        verbosity         = 0,
        # scale_pos_weight set dynamically in DataController
    )

    RANDOM_FOREST = dict(
        n_estimators  = 300,
        max_depth     = 12,
        class_weight  = "balanced",
        random_state  = 42,
        n_jobs        = -1,
    )

    GRADIENT_BOOSTING = dict(
        n_estimators  = 200,
        learning_rate = 0.08,
        max_depth     = 5,
        random_state  = 42,
    )

    LOGISTIC_REGRESSION = dict(
        C            = 1.0,
        solver       = "liblinear",
        class_weight = "balanced",
        random_state = 42,
        max_iter     = 2000,
    )

    # Model display names → colours (for consistent theming)
    MODEL_COLORS = {
        "XGBoost"            : "#ef5350",
        "Random Forest"      : "#26a69a",
        "Gradient Boosting"  : "#42a5f5",
        "Logistic Regression": "#ab47bc",
    }

# ─────────────────────────────────────────────
#  SHAP
# ─────────────────────────────────────────────
class ShapConfig:
    MAX_SAMPLES  = 500    # SHAP computation sample limit (speed vs accuracy)
    TOP_FEATURES = 20

# ─────────────────────────────────────────────
#  BV-BRC API  (for reference / download script)
# ─────────────────────────────────────────────
class BVBRC:
    BASE_URL = "https://www.bv-brc.org/api"

    # Returns AMR phenotype CSV for A. baumannii + Meropenem
    AMR_CSV_URL = (
        "https://www.bv-brc.org/api/genome_amr/"
        "?and(eq(taxon_lineage_ids,470),eq(antibiotic,meropenem))"
        "&select(genome_id,genome_name,antibiotic,resistant_phenotype,"
        "measurement,measurement_unit,laboratory_typing_method)"
        "&limit(10000)"
        "&http_accept=text/csv"
    )

    # Returns specialty (AMR) genes CSV for all A. baumannii genomes
    SP_GENES_URL = (
        "https://www.bv-brc.org/api/sp_gene/"
        "?eq(taxon_lineage_ids,470)"
        "&select(genome_id,property,source,gene,product,identity,query_coverage)"
        "&in(property,(AMR,Drug%20Target))"
        "&limit(500000)"
        "&http_accept=text/csv"
    )

    # BV-BRC browser links (open in browser)
    AMR_BROWSER = "https://www.bv-brc.org/view/Taxonomy/470#view_tab=amr"
    GENOME_BROWSER = "https://www.bv-brc.org/view/Taxonomy/470#view_tab=genomes"